import { createStore } from 'redux';

const list = ["Bars",
      "American (New)",
      "Nightlife",
      "Lounges",
      "Restaurants",
      "American (Traditional)",
      "Burgers",
      "Breakfast & Brunch",
      "Food",
      "Grocery",
      "Cafes",
      "Chinese",
      "Italian",
      "Fast Food",
      "Coffee & Tea",
      "Pubs",
      "Arts & Entertainment",
      "Arcades",
      "Breweries",
      "Videos & Video Game Rental",
      "Books, Mags, Music & Video",
      "Shopping",
      "Food Delivery Services",
      "Pizza",
      "Gluten-Free",
      "Asian Fusion",
      "Soup",
      "Sandwiches",
      "Salad",
      "Seafood",
      "Bakeries",
      "Desserts",
      "Sports Bars",
      "Ice Cream & Frozen Yogurt",
      "Beer, Wine & Spirits",
      "Tapas/Small Plates",
      "Drugstores",
      "Barbeque",
      "Specialty Schools",
      "Education",
      "Cooking Schools",
      "Specialty Food",
      "Wine Bars",
      "Mediterranean",
      "Health Markets",
      "Vegetarian",
      "Portuguese",
      "Diners",
      "German",
      "Delis",
      "Dive Bars",
      "Bistros",
      "Chicken Wings",
      "Meat Shops",
      "Polish",
      "Greek",
      "Sushi Bars",
      "Japanese",
      "Indian",
      "Event Planning & Services",
      "Caterers",
      "Hot Dogs",
      "Mexican",
      "Tex-Mex",
      "Bagels",
      "Donuts",
      "Comfort Food",
      "Cocktail Bars",
      "Ethnic Food",
      "Steakhouses",
      "Korean",
      "Chocolatiers & Shops",
      "Cheese Shops",
      "Irish",
      "Vietnamese",
      "Thai",
      "Middle Eastern",
      "Tea Rooms",
      "Bed & Breakfast",
      "Hotels & Travel",
      "Convenience Stores",
      "Peruvian",
      "Latin American",
      "Hotels",
      "Taiwanese",
      "Tobacco Shops",
      "Do-It-Yourself Food",
      "Buffets",
      "Southern",
      "French",
      "Cajun/Creole",
      "Soul Food",
      "Juice Bars & Smoothies",
      "Caribbean",
      "Fondue",
      "Pakistani",
      "Malaysian",
      "Party & Event Planning",
      "Jazz & Blues",
      "Persian/Iranian",
      "Hookah Bars",
      "Beauty & Spas",
      "Cosmetics & Beauty Supply",
      "Music Venues",
      "Automotive",
      "Gas & Service Stations",
      "Active Life",
      "Bowling",
      "Department Stores",
      "Fashion",
      "Art Galleries",
      "Lebanese",
      "Internet Cafes",
      "Flowers & Gifts",
      "Florists",
      "Venues & Event Spaces",
      "Candy Stores",
      "Pool Halls",
      "Spanish",
      "Party Supplies",
      "Wedding Planning",
      "Dance Clubs",
      "Fruits & Veggies",
      "Beer Bar",
      "Cheesesteaks",
      "Fish & Chips",
      "Salvadoran",
      "Shopping Centers",
      "Outlet Stores",
      "Wholesale Stores",
      "British",
      "Cupcakes",
      "Home Decor",
      "Home & Garden",
      "Furniture Stores",
      "Golf",
      "Vegan",
      "Hawaiian",
      "Gastropubs",
      "Russian",
      "Pretzels",
      "Karaoke",
      "Farmers Market",
      "Shaved Ice",
      "Kitchen & Bath",
      "Professional Services",
      "Arabian",
      "Seafood Markets",
      "Performing Arts",
      "Resorts",
      "Halal",
      "Dim Sum",
      "Churches",
      "Festivals",
      "Religious Organizations",
      "Sporting Goods",
      "Sports Wear",
      "Cuban",
      "Nutritionists",
      "Health & Medical",
      "Mongolian",
      "Casinos",
      "Cinema",
      "Car Wash",
      "Social Clubs",
      "Filipino",
      "Kosher",
      "Gay Bars",
      "Butcher",
      "Discount Store",
      "Argentine",
      "Street Vendors",
      "Food Trucks",
      "Belgian",
      "Cambodian",
      "Hungarian",
      "Szechuan",
      "Wineries",
      "Delicatessen",
      "Pasta Shops",
      "Adult Entertainment",
      "Arts & Crafts",
      "Himalayan/Nepalese",
      "Cantonese",
      "Indonesian",
      "Afghan",
      "Herbs & Spices",
      "Mobile Phones",
      "Electronics",
      "Ticket Sales",
      "Food Stands",
      "CSA",
      "Modern European",
      "Moroccan",
      "Appliances",
      "Gift Shops",
      "Basque",
      "Photography Stores & Services",
      "Amusement Parks",
      "Ethiopian",
      "Tanning",
      "Irish Pub",
      "Home Services",
      "Utilities",
      "Auto Repair",
      "Brazilian",
      "Smog Check Stations",
      "Personal Chefs",
      "Laotian",
      "Creperies",
      "Gelato",
      "Coffeeshops",
      "Tapas Bars",
      "Massage",
      "Colleges & Universities",
      "Hot Pot",
      "Burmese",
      "Live/Raw Food",
      "Bookstores",
      "Adult Education",
      "African",
      "Brasseries",
      "RV Parks",
      "Bubble Tea",
      "Brewing Supplies",
      "Airports",
      "Turkish",
      "Oil Change Stations",
      "Tours",
      "Coffee & Tea Supplies",
      "Colombian",
      "Cafeteria",
      "Scandinavian",
      "Canadian (New)",
      "Poutineries",
      "Bikes",
      "Travel Services",
      "Organic Stores",
      "Local Flavor",
      "Traditional Chinese Medicine",
      "Womens Clothing",
      "Haitian",
      "Austrian",
      "Tires",
      "Food Court",
      "Dominican",
      "Horseback Riding",
      "Scottish",
      "Champagne Bars",
      "Swimming Pools",
      "Patisserie/Cake Shop",
      "Cards & Stationery",
      "Newspapers & Magazines",
      "Pub Food",
      "Parking",
      "Local Services",
      "Bike Repair/Maintenance",
      "Ramen",
      "Landmarks & Historical Buildings",
      "Public Services & Government",
      "Yoga",
      "Fitness & Instruction",
      "Musicians",
      "Couriers & Delivery Services",
      "Personal Shopping",
      "Thrift Stores",
      "Windshield Installation & Repair",
      "Bangladeshi",
      "Australian",
      "Piano Bars",
      "Used, Vintage & Consignment",
      "Ukrainian",
      "Falafel",
      "Hardware Stores",
      "Beer Garden",
      "Baden",
      "Beer Gardens",
      "International",
      "Beverage Store",
      "Sports Clubs",
      "Hiking",
      "Ethnic Grocery",
      "Kebab",
      "Children",
      "Hair Salons",
      "Post Offices",
      "Serbo Croatian",
      "Financial Services",
      "Banks & Credit Unions",
      "Singaporean",
      "Weight Loss Centers",
      "Oriental",
      "Comic Books",
      "Vinyl Records",
      "Distilleries",
      "Dry Cleaning & Laundry",
      "Community Service/Non-Profit",
      "Venezuelan",
      "Leisure Centers",
      "Bavarian",
      "Kids Activities",
      "Toy Stores",
      "Iberian",
      "Trinidadian",
      "Curry Sausage",
      "Shanghainese",
      "Jewelry",
      "Pest Control",
      "Cooking Classes",
      "Country Dance Halls",
      "Pet Services",
      "Pets",
      "Cultural Center",
      "Donairs",
      "Czech",
      "Real Estate",
      "Apartments",
      "Eastern European",
      "Eastern German",
      "Printing Services",
      "Wok",
      "Lakes",
      "Swiss Food",
      "Egyptian",
      "Uzbek",
      "Trainers",
      "Wine Tours",
      "Shared Office Spaces",
      "Pita",
      "Teppanyaki",
      "Day Spas",
      "Izakaya"]
const initialState = {
	latitude: 33.5,
  longitude: -112.0716401,
  categories_list: list,
  hours: []
}
function counter(state = initialState, action, payload) {
	console.log('v', payload)
  switch (action.type) {
	  case 'LATITUDE':
	    return state.latitude = payload.value;
	  case 'LONGITUDE':
	    return state.longitude = payload.value;
	  case 'HOURS':
	    return state.hours.push(payload.value);
	  case 'HIT_API':
	  	passData(state.getState());
	  case 'SET_CATEGORIES':
	  	return state.categories = payload.value
	  default:
	    return state;
	 }
}

// Create a Redux store holding the state of your app.
// Its API is { subscribe, dispatch, getState }.
const store = createStore(counter);

// You can subscribe to the updates manually, or use bindings to your view layer.
store.subscribe(() =>
  console.log(store.getState())
);

//Date.now() -> check the current time during the 
const passData = (state) => {
	const object = {
		latitude: state.latitude,
		longitude: state.longitude,
		time: Date.now(),
		hours: state.hours,
		categories: state.categories
	}
}

module.exports = store;